### ISSUE TITLE
FB login error

### ISSUE THREAD

**Issue by wgod58** [AnomalyInnovations/serverless-stack-demo-fb-login-client#1]
First, reflash your demo page and then use Facebook login. It will alert error every time
  Evert time reflash will happen this issue
  demo page (https://demo-fb-login.serverless-stack.com/login)
OS: Mac Browser: Chrome

**Comment by jayair** [comment]
Hmm I just tested it on my Mac on Chrome and I don't see anything. What is the error you are seeing when you refresh it?

**Comment by wgod58** [comment]
<img width="497" alt="Screen Shot 2019-04-22 at 9 59 36 PM" src="https://user-images.githubusercontent.com/46532844/56504139-343e6380-654a-11e9-89c7-917fa9d66adb.png">

I refresh every time before I login with facebook.
I refer the [facebook](https://developers.facebook.com/docs/facebook-login/web/?locale=en_US) develop document.And then I make some change in App.js function fbAsyncInit. 
And it works good. Never jump alert again
``` javascript
         window.fbAsyncInit = function () {
            FB.init({
                appId: 'XXXXXXXX',
                cookie: true,  // enable cookies to allow the server to access 
                xfbml: true,  // parse social plugins on this page
                version: 'v3.2' // The Graph API version to use for the call
            });
            FB.getLoginStatus(function (response) { // I add this function
                //do something
            });
        };
```

**Comment by wgod58** [comment]
<img width="497" alt="Screen Shot 2019-04-22 at 9 59 36 PM" src="https://user-images.githubusercontent.com/46532844/56504090-09eca600-654a-11e9-90df-6bda2acd480c.png">
